### ISSUE TITLE
NameError: name 'keyboard' is not defined

### ISSUE THREAD

**Issue by supersambo** [DanManN/vim-razer#1]
I installed vim-razer via the AUR package on Arch linux. When starting vim I get the following error message:

```
Error detected while processing /usr/share/vim/vimfiles/plugin/vim_razer.vim:
line   55:
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/usr/lib/python3.6/site-packages/dbus/__init__.py", line 77, in <module
    import dbus.types as types
  File "/usr/lib/python3.6/site-packages/dbus/types.py", line 6, in <module>
    from _dbus_bindings import (
ImportError: /usr/lib/python3.6/site-packages/_dbus_bindings.so: undefined symbol: PyExc_KeyboardInterrupt
Error detected while processing function ResetKeyboardColor:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/share/vim/vimfiles/plugin/mode_colors.py", line 9, in <module>
    mat = keyboard.fx.advanced.matrix
NameError: name 'keyboard' is not defined
```

I have both `+python/dyn` and `+python3/dyn`in my vim installation. However since it's apparently using the correct python version I'm not sure if this is the bug you are writing about in the readme. If it is, how can I disable python2 ?

**Comment by DanManN** [comment]
It is the same bug. To disable python2 in vim you have to compile it yourself without the python option or with the disable python option. If you are using Arch, the easiest way to do this in my opinion is to just install one of the vim versions from the AUR and delete all instances of the line:
--enable-pythoninterp=dynamic \
from the PKGBUILD.
