### ISSUE TITLE
Null Byte Error upon execution

### ISSUE THREAD

**Issue by kyputer** [DanManN/vim-razer#3]
Hello, I am currently experiencing this issue.

Has this been encountered? Is there any known way to remedy this error?
Thanks in advanced!
![2017-11-30-212356_2048x1152_scrot](https://user-images.githubusercontent.com/5109500/33465261-d38cf24c-d614-11e7-8251-0f42d1fabe51.png)

**Comment by DanManN** [comment]
Can you post the full output of vim --version

**Comment by kyputer** [comment]
Hi DanManN,

This is with neovim on arch linux
![2018-10-05-154604_2560x1440_scrot](https://user-images.githubusercontent.com/5109500/46556824-d8660300-c8b5-11e8-911f-a22d2a81461d.png)
![2018-10-05-154651_2560x1440_scrot](https://user-images.githubusercontent.com/5109500/46556839-e3209800-c8b5-11e8-8a52-4b06d13500e3.png)

**Comment by DanManN** [comment]
Weird. I also have neovim and am on arch linux but I can't reproduce your error. Do you have the latest version of the openrazer-daemon and python-openrazer?

**Comment by DanManN** [comment]
old
