### ISSUE TITLE
Doesn't restore the previous lighting effect

### ISSUE THREAD

**Issue by Kusoneko** [DanManN/vim-razer#9]
Hello,

So, after fighting a bit with nvim (mostly because it wouldn't load any of my .{n,neo,}vimrc files), I noticed that when quitting, no matter how I do it, it doesn't restore the lighting state of my Blackwidow Chroma V2, but while it's running it does switch lighting correctly and everything, this is quite annoying. I am not sure either how to check for why this happens. I remember it working fine last year before I switched distro, and since it does work fine besides for this bit, I'm thinking perhaps something updated since and the interface it uses to either restore or possibly get the color state of the keyboard before setting it to vim keybindings is likely the problem. Otherwise, I have no idea what could be causing this.

**Comment by DanManN** [comment]
The openrazer api does seem to change rather frequently from what I remember. I haven't updated this project in a while and it seems there are better alternatives at the moment ([openrgb.nvim](https://github.com/antoinemadec/openrgb.nvim)) so I'm not sure I'll update this anymore. In the summer I'll probably take a closer look at the differences between openrgb.nvim and this plugin and see whether its worth more to update mine or help port the other plugin to regular vim.

**Comment by DanManN** [comment]
probably fixed via mentioned pull request
